# Generated by Django 4.0.3 on 2022-03-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
